Add ZK opcodes definition
FuelLabs/fuel-specs pull request #619
Opened 2024-11-19 18:16 UTC by AurelienFT

https://github.com/FuelLabs/fuel-specs/issues/615

VM PR : https://github.com/FuelLabs/fuel-vm/pull/870

### Before requesting review
- [x] I have reviewed the code myself

### After merging, notify other teams

[Add or remove entries as needed]

- [ ] [Rust SDK](https://github.com/FuelLabs/fuels-rs/)
- [ ] [Sway compiler](https://github.com/FuelLabs/sway/)
- [ ] [Platform documentation](https://github.com/FuelLabs/devrel-requests/issues/new?assignees=&labels=new+request&projects=&template=NEW-REQUEST.yml&title=%5BRequest%5D%3A+) (for out-of-organization contributors, the person merging the PR will do this)
- [ ] Someone else?

2024-11-28 08:07 UTC, rymnc commented on src/fuel-vm/instruction-set.md
> +| Syntax      | `eadd $rA, $rB, $rC, $rD`                           |
should it be ecop here?

```suggestion
| Syntax      | `ecop $rA, $rB, $rC, $rD`                           |
```

2024-11-28 08:07 UTC, rymnc commented on src/fuel-vm/instruction-set.md
> +|    `0`         | `0`                  | `MEM[$rA, 64]` `1P`  | `MEM[$rC, 128]` `1P1P`     |
```suggestion
|    `0`         | `0`                  | `MEM[$rA, 64]` `1P`  | `MEM[$rC, 128]` `1P1S`     |
```

2024-11-28 09:24 UTC, AurelienFT commented
@rymnc thank you for pointing incoherences :)

2024-11-28 09:29 UTC, rymnc approved these changes
LGTM, small nit

2024-11-28 09:29 UTC, rymnc commented on src/fuel-vm/instruction-set.md
> +| Description | This opcode regroups all arithmetic operations that can be perform on elliptic curve points. `$rB` defines the curve used. `$rC` defines the type of operation to perform. `$rD` points
```suggestion
| Description | This opcode regroups all arithmetic operations that can be performed on elliptic curve points. `$rB` defines the curve used. `$rC` defines the type of operation to perform. `$rD` points to the start of the bytes of the operation inputs in memory. `$rA` points to the start of the bytes of the result in memory.                                                   |
```

2024-11-28 10:40 UTC, rymnc approved these changes

2024-11-28 12:41 UTC, Dentosal requested changes
Panic conditions must be described as well. The operations panic at least in cases where mode-selection arguments are not from the list of available modes. Also outputs to memory require that memory to be writeable. Likely there are also cases where the argument values etc. can also be incorrect, in which case the operation should fail. Consider allowing the use of `$err` in those cases.

2024-11-28 12:41 UTC, Dentosal commented on src/fuel-vm/instruction-set.md
> +| Description | Perform a specific pairing type within a specific curve both identified by `$rB`. `$rC` defines the number of batch of groups. `$rD` define where the bytes of the groups of points sta
```suggestion
| Description | Check if `$rC` groups of points at `$rD` all form valid pairings in (curve, pairing type) identified by `$rB`. Set `$rA` to the result of the pairing, either `0` or `1`. |
```

2024-11-28 12:41 UTC, Dentosal commented on src/fuel-vm/instruction-set.md
> +| Description | This opcode regroups all arithmetic operations that can be performed on elliptic curve points. `$rB` defines the curve used. `$rC` defines the type of operation to perform. `$rD` poin
```suggestion
| Description | Perform arithmetic operation `$rC` on points of the elliptic curve `$rB`. Arguments are read from memory at `$rD`, and is result written to the memory at `$rA`, as per the table below.                                                   |
```

2024-11-28 12:46 UTC, Dentosal commented on src/fuel-vm/instruction-set.md
> +| Description | This opcode regroups all arithmetic operations that can be performed on elliptic curve points. `$rB` defines the curve used. `$rC` defines the type of operation to perform. `$rD` poin
Not sure if my wording is exact enough, but I felt like yours was unnecessarily verbose.

2024-11-28 13:52 UTC, AurelienFT commented
@Dentosal I have added panic cases. However, I don't make use of `$err` because I don't really understand in which cases it's better to use that than just make the call fail. 
Following the docs here and a comment on the VM, it seems to be used only on ALU and for me on these opcodes there is no use case for that.

2024-11-29 16:20 UTC, AurelienFT commented
I don't think it's expected and I don't see any logic of modifying the input to retry directly designed in code. Also if the point isn't corrected created in the VM implementation then the addition can't be tried and the code will be more difficult and I think users whould except a panic and this will help them debugging with an explicit reason.

2024-12-02 10:44 UTC, rymnc submitted a review, later dismissed

2025-01-16 15:08 UTC, Dentosal approved these changes

2025-01-16 15:23 UTC, merged